/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (5000) [part_id]
      ,[product_part_no]
      ,[product_part_name]
      ,[product_descp]
      ,[category_id]
      ,[product_drawing_no]
      ,[product_pic_url]
      ,[product_cost]
      ,[product_source_type]
      ,[drawing_img]
      ,[minimum_stock_qty]
      ,[hsn_code]
      ,[material_type]
      ,[vendor_list]
      ,[create_date]
      ,[modify_date]
      ,[closed_by]
      ,[create_by]
      ,[modify_by]
      ,[aproved_by]
      ,[is_active]
  FROM [vekaria_erp].[dbo].[parts_master]